export * from "./Auth/Login/Login";
export * from "./Auth/Register/Register";
export * from "./Dashboard/Dashboard";
export * from "./Not Found/NotFound";
export * from "./Home/Home";
export * from "./Artists/ArtistProfile";
export * from "./Artists/EditArtist";
export * from "./Dashboard/Crew";
export * from "./Dashboard/NewArtist";
export * from "./Clients/NewClient";
